name: Test PRs

on: [pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9.23
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.23
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
        pip install "numpy<2"
        pip install packaging
    - name: Test and build data
      run: |
        python scripts/build_data.py
